name: Unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv wheel
          pipenv install --dev
      - name: Build wheel
        run: |
            pipenv run python -m build
      - name: Run unit tests
        env:
          CTX_USERNAME: ${{ secrets.CTX_USERNAME }}
          CTX_PASSWORD: ${{ secrets.CTX_PASSWORD }}
        run: |
          pipenv run python -m unittest discover tests
